### ISSUE TITLE
PlaceCage down?

### ISSUE THREAD

**Issue by rbvea** [davecowart/placecage#7]
Getting an application error:

![screen shot 2018-04-30 at 1 24 20 pm](https://user-images.githubusercontent.com/949055/39454983-e1455920-4c79-11e8-9c7b-0f75d9758693.png)

![](https://media.giphy.com/media/OAhEs6PXgc2cg/giphy.gif)

**Comment by davecowart** [comment]
Haha, excellent choice of gif. It’s running on a free heroku dyno and it ran out of hours for the month. Sorry for the inconvenience, but it’ll be back tomorrow. Going to work on a solution for that soon.
